User.delete_all
Product.delete_all

u1 = User.create(:email => 'rrrron@gmail.com', :name => 'Ron Jones', :city => 'Amsterdam', :image => 'https://sphotos-a.xx.fbcdn.net/hphotos-ash4/317051_2157624819162_2129388973_n.jpg', :twitter => '@__r__o__n__', :password => 'x', :password_confirmation => 'x')
u2 = User.create(:email => 'archie@gmail.com', :name => 'Archie Bunker', :city => 'Queens, NY', :image => 'http://blog.sarcasmsociety.com/wp-content/uploads/2010/05/ArchieBunker.jpg', :twitter => '@meathead', :password => 'x', :password_confirmation => 'x')
u3 = User.create(:email => 'cliff@gmail.com', :name => 'Heathcliff Huxtable', :city => 'Brooklyn, NY', :image => 'http://3.bp.blogspot.com/_kPH0ZxIXBA8/S27hmFGWNvI/AAAAAAAAHUw/P9rMdbUvpRI/s400/bill+cosby.jpg', :twitter => '@puddingpop', :password => 'x', :password_confirmation => 'x')

p1 = Product.create(:prod_image => 'http://3.bp.blogspot.com/-GOkxeK7oGPE/UDg5Cn7fkYI/AAAAAAAAEno/-7YAlGG674c/s1600/jell-o+turtle+sundae+pudding+snack.jpg', :prod_name => 'Jello Mix Ins-Turtle Sundae', :prod_type => 'food', :company_name => 'Jello', :upc => '043000051092', :description => 'Pudding in plastic cups? What happened to eating it out of your hands?', :company_twitter => '@jello')
p2 = Product.create(:prod_image => 'http://www.thedailygreen.com/cm/thedailygreen/images/P2/packaged-food-gd5-lg.jpg', :prod_name => 'Earthbound Farm Raisins', :prod_type => 'food', :company_name => 'Earthbound Farm', :upc => '032601050306', :description => 'Raisins packaged in individual boxes in a big plastic bag. WTF?', :company_twitter => '@earthboundfarm')
p3 = Product.create(:prod_image => 'http://www.thedailygreen.com/cm/thedailygreen/images/Dv/packaged-food-gd4-lg.jpg', :prod_name => 'Mt Olive Pickle Pack', :prod_type => 'food', :company_name => 'Mt Olive', :upc => '0930010014', :description => 'Single serving pickles packaged in 4oz plastic cups? WTF?', :company_twitter => '@OllieQCumber')
p4 = Product.create(:prod_image => 'http://www.thedailygreen.com/cm/thedailygreen/images/7K/packaged-food-gd3-lg.jpg', :prod_name => 'Cracker Barrel Cheddar Cheese Sticks', :prod_type => 'food', :company_name => 'Kraft', :upc => '021000626373', :description => 'Small portions of cheese wrapped in plastic inside a larger bag of plastic. WTF?', :company_twitter => '@kraftfoods')
p5 = Product.create(:prod_image => 'http://media.treehugger.com/assets/images/2011/10/bad-packaging-design-individually-wrapped-bananas-photo.jpg.644x0_q100_crop-smart.jpg', :prod_name => 'Banana', :prod_type => 'food', :company_name => 'Tesco', :upc => '', :description => 'A fruit with its own natural packaging wrapped in styrofoam and plastic? WTF?', :company_twitter => '@UKTesco')
p6 = Product.create(:prod_image => 'http://www.blogcdn.com/www.joystiq.com/media/2008/12/gam_clamshellears_490.jpg', :prod_name => 'Sennheiser HD 555 Headphones', :prod_type => 'electronics', :company_name => 'Sennheiser', :upc => '015104053425', :description => 'Elaborate clamshell cardboard box with molded plastic insert. Way overpackaged.', :company_twitter => '@SennheiserUSA')
p7 = Product.create(:prod_image => 'http://farm3.staticflickr.com/2684/4491243565_96bbf203cd_z.jpg', :prod_name => 'HP Inkjet Cartridge', :prod_type => 'electronics', :company_name => 'HP', :upc => '829160920979', :description => 'Massive amounts of plastic around a small ink cartridge. Terrible.', :company_twitter => '@HP')
p8 = Product.create(:prod_image => 'http://paulspurling.blogspot.com/2012/01/pet-peeve-wasteful-packaging.html', :prod_name => 'Amazon shipment packaging', :prod_type => 'shipping', :company_name => 'Amazon', :upc => '', :description => 'Big box and filler for a tiny HDMI adapter- why couldnt they just use an envelope?', :company_twitter => '@amazon')
p9 = Product.create(:prod_image => 'http://sayiamgreen.com/blog/wp-content/uploads/books.jpg', :prod_name => 'Playaway Single use Audiobook', :prod_type => 'electronics', :company_name => 'Playaway', :upc => '159895007X', :description => 'A media player that only exists to play the audio of one book. Ridiculous!', :company_twitter => '@PLAYAWAY')

u1.products = [p1, p4, p7]
u2.products = [p2, p5, p8]
u3.products = [p3, p6, p9]